import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.scss";
import Header from "./components/header/Header";
import { Providers } from "./providers";

const inter = Nunito({ subsets: ["latin"], variable: "--font-nunito" });

export const metadata: Metadata = {
  title: "ABZ agency test task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <Header />
          {children}
        </body>
      </Providers>
    </html>
  );
}
